x-logging: &default-logging
  driver: json-file
  options:
    max-size: "${LOG_MAX_SIZE:-1m}"
    max-file: "${LOG_MAX_FILES:-3}"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: ${SERVICE_NAME}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    user: "1000:1000"
    networks:
      - traefik
    ports:
      - "${HTTP_PORT:-8096}:8096/tcp"
      - "${DISCOVERY_PORT:-7359}:7359/udp"
    volumes:
      - ${CONTAINER_DIR}/config:/config
      - ${CONTAINER_DIR}/cache:/cache
      - type: bind
        source: ${CONTAINER_DIR}/media
        target: /media
      - type: bind
        source: ${CONTAINER_DIR}/media2
        target: /media2
        read_only: true
      - type: bind
        source: ${CONTAINER_DIR}/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
      - /mnt/nvme1/Services/Jellyfin/Movies:/movies:ro
    environment:
      TZ: ${TZ}
      JELLYFIN_PublishedServerUrl: ${VIRTUAL_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin.service=jellyfin-srv"
      - "traefik.http.services.jellyfin-srv.loadbalancer.server.port=8096"
    logging: *default-logging

networks:
  traefik:
    external: true