x-logging: &default-logging
  driver: json-file
  options:
    max-size: "${LOG_MAX_SIZE:-2m}"
    max-file: "${LOG_MAX_FILES:-3}"

services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    container_name: ${SERVICE_NAME}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      - "${GAME_PORT:-8211}:8211/udp"
      - "${QUERY_PORT:-27015}:27015/udp"
    volumes:
      - ${CONTAINER_DIR}/data:/palworld
    environment:
      TZ: ${TZ}
    mem_limit: ${MEM_LIMIT:-8g}
    logging: *default-logging