FROM quay.io/jupyterhub/jupyterhub:latest
RUN pip install --no-cache-dir jupyterhub-nativeauthenticator jupyterlab notebook jupyter-collaboration
RUN pip install --no-cache-dir pandas numpy matplotlib scikit-learn seaborn xgboost
