x-logging: &default-logging
  driver: json-file
  options:
    max-size: "${LOG_MAX_SIZE:-1m}"
    max-file: "${LOG_MAX_FILES:-3}"

services:
  gpsno:
    image: ghcr.io/legincy/gpsno-server:latest
    container_name: ${SERVICE_NAME}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    networks:
      - traefik
    volumes:
      - ${CONTAINER_DIR}/data:/data
    environment:
      TZ: ${TZ}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      DB_PATH: /data/gpsno_mappings.db
      WEB_PORT: "5000"
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gpsno.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.gpsno.entrypoints=websecure"
      - "traefik.http.routers.gpsno.service=gpsno-srv"
      - "traefik.http.services.gpsno-srv.loadbalancer.server.port=5000"
    logging: *default-logging

networks:
  traefik:
    external: true